name: "CI [branch]"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.13.0"
          cache: true

      - uses: actions/checkout@v4

      - name: Install dependencies
        run: flutter pub get

      - name:  Analyze project source
        run: |
          flutter analyze --fatal-infos
          dart format --set-exit-if-changed .

      - name: Run tests
        run: flutter test
